### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/infografia-Abraham890#2]
[INFOGRAFIA_ABRAHAM_REYES_ORTIZ.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Abraham890/files/7151149/INFOGRAFIA_ABRAHAM_REYES_ORTIZ.pdf)

**Comment by Arnold-Js** [comment]
califico Arnol Jesus Cruz Ortiz
Calificación: 18

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
